name: movie_tracking
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  provider: ^6.0.2
  equatable: ^2.0.3
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
